version: '2'
services:
  anon-how-to-pandocker:
    image: dalibo/pandocker:latest
    environment:
      - PGHOST=anon-how-to-postgresql
      - PGPASSWORD=CHANGEME
      - PGUSER=postgres
    volumes:
      - .:/pandoc
#    links:
#      - anon-how-to-postgresql
    entrypoint: /bin/bash
    tty: true
    #command: 'init_postgres.sh && sleep infinity'
    #command: 'init_postgres.sh && make how-to -B && sleep infinity'

#  anon-how-to-postgresql:
#    image: registry.gitlab.com/dalibo/postgresql_anonymizer:1.1.0
#    environment:
#      - POSTGRES_PASSWORD=CHANGEME
#      - PGUSER=postgres
#    expose:
#      - 5432
