apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: 'test'
  namespace: postgres
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
      postInitApplicationSQL:
      - >-
        CREATE EXTENSION IF NOT EXISTS anon CASCADE; SELECT anon.init(); SELECT pg_reload_conf();
      postInitSQL:
      - >-
        CREATE EXTENSION IF NOT EXISTS anon CASCADE; SELECT anon.init(); SELECT pg_reload_conf();
      postInitTemplateSQL:
      - >-
        CREATE EXTENSION IF NOT EXISTS anon CASCADE; SELECT anon.init(); SELECT pg_reload_conf();
  enablePDB: true
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/sevifinance/pggisanon:30
  imagePullSecrets:
  - name: ghrcio
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      enableAlterSystem: 'true'
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      max_parallel_workers: '32'
      max_replication_slots: '32'
      max_slot_wal_keep_size: 5GB
      max_worker_processes: '32'
      shared_memory_type: mmap
      shared_preload_libraries: ''
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: 'on'
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    shared_preload_libraries:
    - anon
    - timescaledb
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: '3'
      memory: 3Gi
    requests:
      cpu: '2'
      memory: 3Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 1Gi
    storageClass: longhorn
  switchoverDelay: 3600
