---
version: '3'

services:
  PostgreSQL:
    image: registry.gitlab.com/dalibo/postgresql_anonymizer
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=CHANGEME
      - PGUSER=postgres    # required for `make installcheck`
    volumes:
      - $PWD:/tmp/source
    working_dir: /tmp/source
    command: >
      postgres  -c shared_preload_libraries='anon'
                -c hba_file=/tmp/source/pg_dump_anon/tests/pg_hba.conf
